development:
  adapter: postgresql
  database: test_test
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000
  port: 5434

test:
  adapter: postgresql
  database: test_test
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000
  port: 5434

production:
  adapter: postgresql
  database: test
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000
  port: 5434
